config/routes.rb
Rails.application.routes.draw do


  resources :counsels

  resources :diagnoses

  devise_for :users
  resources :patients do
  	resources :medical_records
  end

  root "patients#index"

end

app/models/counsel.rb
class Counsel < ActiveRecord::Base
  belongs_to :diagnosis
  has_many :medical_records
end

app/controllers/counsels_controller.rb
class CounselsController < ApplicationController
  before_action :set_counsel, only: [:show, :edit, :update, :destroy]

  # GET /counsels
  # GET /counsels.json
  def index
    @counsels = Counsel.all
  end

  # GET /counsels/1
  # GET /counsels/1.json
  def show
  end

  # GET /counsels/new
  def new
    @counsel = Counsel.new
  end

  # GET /counsels/1/edit
  def edit
  end

  # POST /counsels
  # POST /counsels.json
  def create
    @counsel = Counsel.new(counsel_params)

    respond_to do |format|
      if @counsel.save
        format.html { redirect_to @counsel, notice: 'Counsel was successfully created.' }
        format.json { render :show, status: :created, location: @counsel }
      else
        format.html { render :new }
        format.json { render json: @counsel.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /counsels/1
  # PATCH/PUT /counsels/1.json
  def update
    respond_to do |format|
      if @counsel.update(counsel_params)
        format.html { redirect_to @counsel, notice: 'Counsel was successfully updated.' }
        format.json { render :show, status: :ok, location: @counsel }
      else
        format.html { render :edit }
        format.json { render json: @counsel.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /counsels/1
  # DELETE /counsels/1.json
  def destroy
    @counsel.destroy
    respond_to do |format|
      format.html { redirect_to counsels_url, notice: 'Counsel was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_counsel
      @counsel = Counsel.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def counsel_params
      params.require(:counsel).permit(:name, :counsel)
    end
end

app/helpers/counsels_helper.rb
module CounselsHelper
end

app/views/counsels/_form.html.erb
<%= form_for(@counsel) do |f| %>
  <% if @counsel.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@counsel.errors.count, "error") %> prohibited this counsel from being saved:</h2>

      <ul>
      <% @counsel.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :name %>
    <%= f.text_field :name, class: "form-control" %>
  </div>
  <div class="form-group">
    <%= f.label :counsel %>
    <%= f.text_area :counsel, class: "form-control", rows: 15 %>
  </div>
  <div class="form-group">
    <%= f.submit class: "btn btn-primary" %>
  </div>
<% end %>

app/views/counsels/edit.html.erb
<h1>Editing Counsel</h1>

<%= render 'form' %>

<%= link_to 'Show', @counsel %> |
<%= link_to 'Back', counsels_path %>

app/views/counsels/index.html.erb
<h1>Listing Counsels</h1>

<table class="table table-striped table-hover">
  <thead>
    <tr>
      <th>#</th>
      <th>Diagnosis</th>
      <th>Counsel</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @counsels.each do |counsel| %>
      <tr>
        <td><%= counsel.id %></td>
        <td><%= counsel.name %></td>
        <td><%= excerpt(counsel.counsel, 'Your', radius: 75) %></td>
        <td><%= link_to 'Show', counsel %></td>
        <td><%= link_to 'Edit', edit_counsel_path(counsel) %></td>
        <td><%= link_to 'Destroy', counsel, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Counsel', new_counsel_path %>

app/views/counsels/new.html.erb
<h1>New Counsel</h1>

<%= render 'form' %>

<%= link_to 'Back', counsels_path %>

app/views/counsels/show.html.erb
<p>
  <strong>Diagnosis:</strong>
  <%= @counsel.name %>
</p>
<p>
  <strong>Counsel:</strong>
  <%= simple_format(@counsel.counsel) %>
</p>

<%= link_to 'Edit', edit_counsel_path(@counsel) %> |
<%= link_to 'Back', counsels_path %>