config/routes.rb
Rails.application.routes.draw do


  resources :counsels

  resources :diagnoses

  devise_for :users
  resources :patients do
  	resources :medical_records
  end

  root "patients#index"

end

app/controllers/diagnoses_controller.rb
class DiagnosesController < ApplicationController
  before_action :set_diagnosis, only: [:show, :edit, :update, :destroy]

  # GET /diagnoses
  # GET /diagnoses.json
  def index
    @diagnoses = Diagnosis.all
  end

  # GET /diagnoses/1
  # GET /diagnoses/1.json
  def show
  end

  # GET /diagnoses/new
  def new
    @diagnosis = Diagnosis.new
  end

  # GET /diagnoses/1/edit
  def edit
  end

  # POST /diagnoses
  # POST /diagnoses.json
  def create
    @diagnosis = Diagnosis.new(diagnosis_params)

    respond_to do |format|
      if @diagnosis.save
        format.html { redirect_to @diagnosis, notice: 'Diagnosis was successfully created.' }
        format.json { render :show, status: :created, location: @diagnosis }
      else
        format.html { render :new }
        format.json { render json: @diagnosis.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /diagnoses/1
  # PATCH/PUT /diagnoses/1.json
  def update
    respond_to do |format|
      if @diagnosis.update(diagnosis_params)
        format.html { redirect_to @diagnosis, notice: 'Diagnosis was successfully updated.' }
        format.json { render :show, status: :ok, location: @diagnosis }
      else
        format.html { render :edit }
        format.json { render json: @diagnosis.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /diagnoses/1
  # DELETE /diagnoses/1.json
  def destroy
    @diagnosis.destroy
    respond_to do |format|
      format.html { redirect_to diagnoses_url, notice: 'Diagnosis was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_diagnosis
      @diagnosis = Diagnosis.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def diagnosis_params
      params.require(:diagnosis).permit(:name)
    end
end

app/helpers/diagnoses_helper.rb
module DiagnosesHelper
end

app/views/diagnoses/_form.html.erb
<%= form_for(@diagnosis) do |f| %>
  <% if @diagnosis.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@diagnosis.errors.count, "error") %> prohibited this diagnosis from being saved:</h2>

      <ul>
      <% @diagnosis.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/diagnoses/edit.html.erb
<h1>Editing Diagnosis</h1>

<%= render 'form' %>

<%= link_to 'Show', @diagnosis %> |
<%= link_to 'Back', diagnoses_path %>

app/views/diagnoses/index.html.erb
<h1>Listing Diagnoses</h1>

<table class="table table-striped">
  <thead>
    <tr>
      <th>Name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @diagnoses.each do |diagnosis| %>
      <tr>
        <td><%= diagnosis.name %></td>
        <td><%= link_to 'Show', diagnosis %></td>
        <td><%= link_to 'Edit', edit_diagnosis_path(diagnosis) %></td>
        <td><%= link_to 'Destroy', diagnosis, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Diagnosis', new_diagnosis_path %>

app/views/diagnoses/new.html.erb
<h1>New Diagnosis</h1>

<%= render 'form' %>

<%= link_to 'Back', diagnoses_path %>

app/views/diagnoses/show.html.erb
<p>
  <strong>Name:</strong>
  <%= @diagnosis.name %>
</p>

<%= link_to 'Edit', edit_diagnosis_path(@diagnosis) %> |
<%= link_to 'Back', diagnoses_path %>