config/routes.rb
Rails.application.routes.draw do


  resources :counsels

  resources :diagnoses

  devise_for :users
  resources :patients do
  	resources :medical_records
  end

  root "patients#index"

end

app/models/patient.rb
class Patient < ActiveRecord::Base
	belongs_to :user
	has_many :medical_records, dependent: :destroy
	after_create :set_mrn

	Gender = %w(Male Female)

	validates :name, :gender, :phone, presence: true
	validates :name, uniqueness: {scope: :phone, message: ' with this phone number is already registered in the system.'}

	def set_mrn
		if self.id < 10
			update_attribute(:mrn, "DR00#{self.id}C")
		elsif self.id < 100
			update_attribute(:mrn, "DR0#{self.id}C")
		elsif self.id < 1000
			update_attribute(:mrn, "DR0#{self.id}C")
		else
			update_attribute(:mrn, "DR#{self.id}C")
		end
	end
end

app/controllers/patients_controller.rb
class PatientsController < ApplicationController
  before_filter :authenticate_user!
  before_action :set_patient, only: [:show, :edit, :update, :destroy]

  # GET /patients
  # GET /patients.json
  def index
    @search = Patient.search(params[:q])
    @patients = @search.result
  end

  # GET /patients/1
  # GET /patients/1.json
  def show
  end

  # GET /patients/new
  def new
    @patient = Patient.new
  end

  # GET /patients/1/edit
  def edit
  end

  # POST /patients
  # POST /patients.json
  def create
    @patient = Patient.new(patient_params)

    respond_to do |format|
      if @patient.save
        format.html { redirect_to @patient, notice: 'Patient was successfully created.' }
        format.json { render :show, status: :created, location: @patient }
      else
        format.html { render :new }
        format.json { render json: @patient.errors, status: :unprocessable_entity }
      end
    end
  end
  
  # PATCH/PUT /patients/1
  # PATCH/PUT /patients/1.json
  def update
    respond_to do |format|
      if @patient.update(patient_params)
        format.html { redirect_to @patient, notice: 'Patient was successfully updated.' }
        format.json { render :show, status: :ok, location: @patient }
      else
        format.html { render :edit }
        format.json { render json: @patient.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /patients/1
  # DELETE /patients/1.json
  def destroy
    @patient.destroy
    respond_to do |format|
      format.html { redirect_to patients_url, notice: 'Patient was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_patient
      @patient = Patient.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def patient_params
      params.require(:patient).permit(:mrn, :name, :gender, :age, :phone, :diabetic, :diab_duration, :hypertensive, :hyp_duration, :va_re, :va_le, :iop_re, :iop_le, :hbaic)
    end
end

app/helpers/patients_helper.rb
module PatientsHelper
end

app/views/patients/_form.html.erb
<%= form_for(@patient) do |f| %>
  <% if @patient.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@patient.errors.count, "error") %> prohibited this patient from being saved:</h2>

      <ul>
      <% @patient.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :name %>
    <%= f.text_field :name, class: "form-control" %>
  </div>
  <div class="form-group">
    <%= f.label :gender %>
    <%= f.select :gender, Patient::Gender, {include_blank: true}, {class: "form-control"} %>
  </div>
  <div class="form-group">
    <%= f.label :age %>
    <%= f.text_field :age, class: "form-control" %>
  </div>
  <div class="form-group">
    <%= f.label :phone %>
    <%= f.text_field :phone, class: "form-control" %>
  </div>
  <div class="form-group">
    <%= f.check_box :diabetic %>
    <%= f.label :diabetic %>
  </div>
  <div class="form-group">
    <%= f.label :diab_duration %>
    <%= f.text_field :diab_duration, class: "form-control" %>
  </div>
  <div class="form-group">
    <%= f.check_box :hypertensive %>
    <%= f.label :hypertensive %>
  </div>
  <div class="form-group">
    <%= f.label :hyp_duration %>
    <%= f.text_field :hyp_duration, class: "form-control" %>
  </div>
  <p>Visual Acuity</p>
  <div class="form-group">
    <%= f.label :va_re, 'RE' %>
    <%= f.text_field :va_re, class: "form-control" %>
  </div>
  <div class="form-group">
    <%= f.label :va_le, 'LE' %>
    <%= f.text_field :va_le, class: "form-control" %>
  </div>
  <hr>
  <p>IOP</p>
  <div class="form-group">
    <%= f.label :iop_re, 'RE' %>
    <%= f.text_field :iop_re, class: "form-control" %>
  </div>
  <div class="form-group">
    <%= f.label :iop_le, 'LE' %>
    <%= f.text_field :iop_le, class: "form-control" %>
  </div>
  <div class="form-group">
    <%= f.label :hbaic %>
    <%= f.text_field :hbaic, class: "form-control" %>
  </div>
  <div class="form-group">
    <%= f.submit "Save", class: "btn btn-primary" %> <%= f.submit class: "btn btn-primary" %>
  </div> 
<% end %>

app/views/patients/edit.html.erb
<h1>Editing Patient</h1>

<%= render 'form' %>

<%= link_to 'Show', @patient %> |
<%= link_to 'Back', patients_path %>

app/views/patients/index.html.erb
<%= search_form_for(@search) do |s| %>
<div class="form-inline">
  <%= s.label :name_or_mrn_cont, "Name/MRN" %>
  <%= s.search_field :name_or_mrn_cont,  class: "form-control" %>
  <%= s.label :gender_eq, "Gender" %>
  <%= s.select :gender_eq, Patient::Gender, {include_blank: true}, {class: "form-control"} %>
  <%= s.label :created_at_gteq, "From: " %>
  <%= s.date_field :created_at_gteq, {class: "form-control"} %>
  <%= s.label :created_at_lteq, "To: " %>
  <%= s.date_field :created_at_lteq, {class: "form-control"} %>
  <%= s.submit class: "btn btn-danger" %>
</div>
<% end %>
<hr>
<p><strong>Total: </strong><%= @patients.count %></p>
<table class="table table-hover table-striped">
  <thead>
    <tr>
      <th>Mrn</th>
      <th>Name</th>
      <th>Gender</th>
      <th>Date of Registration</th>
      <th>Diagnosis RE</th>
      <th>Diagnosis LE</th>
      <th colspan="5"></th>
    </tr>
  </thead>

  <tbody>
    <% @patients.each do |patient| %>
      <tr>
        <td><%= patient.mrn %></td>
        <td><%= patient.name %></td>
        <td><%= patient.gender %></td>
        <td><%= patient.created_at.to_date %></td>
        <% if patient.medical_records.exists? %>
          <td><%= patient.medical_records.last.diag_re %></td> 
          <td><%= patient.medical_records.last.diag_le %></td>
        <% else %>
        <td>No Medical record yet</td>
        <td>No Medical record yet</td>
        <% end %>
        <td><%= link_to 'New Record', new_patient_medical_record_path(patient) %></td>
        <td><%= link_to 'View Records', patient_medical_records_path(patient) %></td>
        <td><%= link_to 'Show', patient %></td>
        <td><%= link_to 'Edit', edit_patient_path(patient) %></td>
        <td><% link_to 'Destroy', patient, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Patient', new_patient_path %>

app/views/patients/new.html.erb
<h1>New Patient</h1>

<%= render 'form' %>

<%= link_to 'Back', patients_path %>

app/views/patients/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Mrn:</strong>
  <%= @patient.mrn %>
</p>

<p>
  <strong>Name:</strong>
  <%= @patient.name %>
</p>

<p>
  <strong>Gender:</strong>
  <%= @patient.gender %>
</p>

<p>
  <strong>Age:</strong>
  <%= @patient.age %>
</p>

<p>
  <strong>Phone:</strong>
  <%= @patient.phone %>
</p>

<p>
  <strong>Diabetic:</strong>
  <%= @patient.diabetic %>
</p>

<p>
  <strong>Diab duration:</strong>
  <%= @patient.diab_duration %>
</p>

<p>
  <strong>Hypertensive:</strong>
  <%= @patient.hypertensive %>
</p>

<p>
  <strong>Hyp duration:</strong>
  <%= @patient.hyp_duration %>
</p>

<p>
  <strong>VA(RE):</strong>
  <%= @patient.va_re %>
</p>

<p>
  <strong>VA(LE):</strong>
  <%= @patient.va_le %>
</p>

<p>
  <strong>IOP(RE):</strong>
  <%= @patient.iop_re %>
</p>

<p>
  <strong>IOP(LE):</strong>
  <%= @patient.iop_le %>
</p>

<p>
  <strong>HbAic:</strong>
  <%= @patient.hbaic %>
</p>

<%= link_to 'Edit', edit_patient_path(@patient) %> |
<%= link_to 'Back', patients_path %>